### ISSUE TITLE
 screenshot of frame when one car crosses the specified line

### ISSUE THREAD

**Issue by Iman1221** [opendatacam/opendatacam#376]
Thank you for the project provided.
How can I get an screenshot of frame when one car crosses the specified line?
Is there any way?

**Comment by vsaw** [comment]
There was a discussion about this where this in https://github.com/opendatacam/opendatacam/issues/170.

Long story short, it was decided by the project owners that this is against Opendatacams "privacy by design" principle. However, there's nothing stopping you from forking Opendatacam and implementing it yourself. ;-)

**Comment by haviduck** [comment]
since odc calls darknet directly, you gonna have to work with the api and grab your frame from the mjpeg stream on the relevant sse event.

**Comment by vsaw** [comment]
@haviduck Thanks! That's exactly what I do, works like a charm :-)
