### ISSUE TITLE
Design & Feature Implem v2

### ISSUE THREAD

**Issue by b-g** [opendatacam/opendatacam#60]
### Current todo list ( @tdurand edit)

- [x]  Bug: counter number when line popup is closed should sum all individual things, seems to take only cars
- [x]  Bug: FPS computation if no detections goes up like crazy
- [x]  Loading screen (init neural network) should have access to the console to see if there was any error
- [x]  Add footer in side menu
- [x]  Persists user settings
- [x]  Implement action behind Toggle Pathfinder & Counter (currently don't do anything)
- [x]  Persists recording settings on Opendatacam server (counter / pathfinder enabled)
- [x]  Responsiveness : Menu mobile, just hide the nav bar and put the link inside the menu
- [x]  Responsiveness: Reduce font-size on smaller devices
- [x]  Data view screen : CSV Export for counter data
- [x] Font size , was developing on ubuntu and now seems really big on mac.. need to fix this
- [x] Bug : If counter disabled, tracker data isn't recorded

### Later improvements:

- [ ]  Data view screen: Optimize perfs (currently re-render every tick) + only render current recording if page = 0
- [ ]  Android chrome: bug when returning from input entry, canvas doesn't re-render correctly (going from a tab to another solves it)... Also seems stream out of sync but maybe because of wifi connexion... Maybe add fulllscreen mode
- [ ] Safari mobile on iPhone SE: but with innerHeight and height: 100% not consistent.. try to make something more robust
- [ ] Add routing to be able to use back button

### Initial post

Hi @tdurand, first round of wireframes ... happy to get feedback on these. Markus @mmmmmmmmmmmmmmmm is working also on a more "incremental" concept. Markus will them post here too ... lets aim to decide on the final concept this Friday in our call. 

**01-init-stream**
![01-init-stream](https://user-images.githubusercontent.com/480224/51486704-b3809780-1da1-11e9-8e6a-88bdad2c30fa.png)

**02-liveview**
![02-liveview](https://user-images.githubusercontent.com/480224/51486705-b3809780-1da1-11e9-8376-ced74c4c1b09.png)

**03-counter**
![03-counter](https://user-images.githubusercontent.com/480224/51486707-b3809780-1da1-11e9-8c2b-496ae5d3f150.png)

**03-counter---line-detail**
![03-counter---line-detail](https://user-images.githubusercontent.com/480224/51486706-b3809780-1da1-11e9-8070-c66163d24dd1.png)

**04-pathfinder**
![04-pathfinder](https://user-images.githubusercontent.com/480224/51486709-b4192e00-1da1-11e9-941f-7ee2e84c7335.png)

**05-data**
![05-data](https://user-images.githubusercontent.com/480224/51486710-b4192e00-1da1-11e9-9c42-d3f47328c77f.png)

**06-console**
![06-console](https://user-images.githubusercontent.com/480224/51486712-b4192e00-1da1-11e9-96d9-b38be345168c.png)

**07-settings**
![07-settings](https://user-images.githubusercontent.com/480224/51486713-b4192e00-1da1-11e9-9c1c-232514abd433.png)

**Comment by mmmmmmmmmmmmmmmm** [comment]
Hi @tdurand @b-g , I have the second approach ready, pretty much the same what we have already but with the new features. 

![mobile](https://user-images.githubusercontent.com/12696639/51530280-e165ea80-1e3a-11e9-8884-f0aa5a543969.jpg)

**Comment by tdurand** [comment]
@b-g @mmmmmmmmmmmmmmmm thanks, I think there are great ideas, some more thought (not super organized), and happy to discuss everything on friday

- I think we should go for a larger rethinking of the flow like what @b-g has prototyped, as opendatacam can be used without counting anything (just to visualize paths for example), and in the future it might include even more "modes".. and counting is just one of them.

- Now once you have opened opendatacam, it is always tracking and give a live feedback of stuff happening as YOLO + Tracker are always running.. So the "record button" now should be named "Start recording" / "Stop recording". And maybe have something like a red border on top when you are recording _(something similar as when on iOS you have a blue bar when an app is using your GPS ...)_

- It would be nice to have feedback as you draw the counting lines whether they are counting stuff or not, and have the bbox color changing to know if it works. 

- I really like the idea to unify the counter view and get rid of the carousel 👍 , this makes thing much simpler _(also implementation wise the carousel was a nightmare in order to handle different screen radio / video ratio)_

- On the flow of bene, I think once you click on the "counter" button  , if no counting line are defined yet we need to use the old flow there with a message "Draw lines where you want to count things"  blablabla .. and yes I think it's the time to add the idea of markus to be able to name those counting lines and not just have yellow / blue in the export.

- In the live view (which will be the default I think) what happen if we click the start recording button and have no counting lines defined ? I think we just record the raw data... But maybe we display some message so the counter mode is a bit more discoverable...  

- In the counting view, in order to make discoveable the existence of the details of the counter, maybe have a little button along with the number of things counted ? not sure what icon it should be...

- I like the idea of introducing a menu to be able to add more info (like about github version number ..), but I think the toggles there for the counter and the pathfinder are confusing... as the pathfinder will always be on, and we have a global Start / Stop recording mode

- Very much agree on having a data / console panel 👍

**Comment by b-g** [comment]
@tdurand @mmmmmmmmmmmmmmmm Many thanks! Lets let it sink and then discuss everything on Friday. Looking forward!

**Comment by mmmmmmmmmmmmmmmm** [comment]
@tdurand I have the next iteration ready, I think it's pretty straight forward based on what we discussed on Tuesday. Next week I will focus more on the details. Let me know what you think!

![artboard](https://user-images.githubusercontent.com/12696639/52119174-9311d200-2618-11e9-8675-dcacad3c31d5.png)

**Comment by tdurand** [comment]
Thanks + great... Some quick feedback:

-  In the menu I think the on / off states should look like toggle, here it's not easy for me to understand if I click on it if I'm disabling / enabling...
-  We could use more screens states for the counting mode to sort out how it will work exactly. Remember there will be a mode when we are not recording where you define the counting lines and name them, and a mode where you can expand and view the counting stats, it would be nice if you could separate those. And try to work on the "edge" case, no line defined yet, how to rename them, 
- I'm missing a screen to show when we are recording with the "currently recording" status bar.
- the labels should be "start recording" / "stop recording"

Also FYI I'm currently refactoring the whole codebase as many things are changing in both backend and frontend,  not rewriting from scratch but getting rid of lots of stuff instead of working around a proof of concept that was not though to beeing extendable.. So not much to show this week but next week I should have a working version that you will be able to try..

**Comment by b-g** [comment]
Hi @mmmmmmmmmmmmmmmm, many thanks for this! Nice first minimal iteration. I've annotated your image with more detailed comments. Happy to have a quick call on this if helpful. Could you manage another iteration for our meeting on Thursday?

![ui-concept-odc_v2-comments-bg](https://user-images.githubusercontent.com/480224/52200136-31e03d80-2868-11e9-8322-95ff77794676.png)

**Comment by mmmmmmmmmmmmmmmm** [comment]
Next iteration, see you in a bit to discuss it :)!

![artboard 2](https://user-images.githubusercontent.com/12696639/52419651-c5c43a80-2af0-11e9-953f-9423eefb92e1.jpg)

**Comment by tdurand** [comment]
Some quick update, I didn't had time to have a live deployment working for you to test of the work in progress but you can run it yourself on your machine by:

- switching to the `0.3` branch
- npm install
- npm run start
- open localhost:8080

Would be nice if you can experiment a bit with it for tomorrow meeting.

If you don't have time, here is a quick screencast of the current state: https://www.youtube.com/watch?v=omuAi0D-2RU&feature=youtu.be

**Comment by mmmmmmmmmmmmmmmm** [comment]
![artboard 2](https://user-images.githubusercontent.com/12696639/52848843-05ea7500-3110-11e9-8776-c36a97ad511b.jpg)

**Comment by tdurand** [comment]
Made some progress this week on this.. Since last update you can at least try the new flow for defining the counting lines (without design refined)

I need to spend ~ 1 more day to get the "invisible" stuff done, but then It would be more productive if we can have the next design iteration + the sketch file for me to implement. 

Next week I have good availabilities so I aim to push 3 more days of work and aim to have a first "beta" ready

**Comment by tdurand** [comment]
_PS: you might get mongodb error in the console by running it as I'm working on the persistence of the recording etc etc .. but the front-end should still work without it._

**Comment by b-g** [comment]
Hi @tdurand, Great! I'm more or less back in office from tomorrow on. Will ping @mmmmmmmmmmmmmmmm whether a call Tue 14°° CET would be doable. Looking forward to hear the latest, B

**Comment by tdurand** [comment]
From my side it's OK for a call tomorrow

**Comment by tdurand** [comment]
Some quick update so we can discuss the screencast demo for monday, cc @b-g @mmmmmmmmmmmmmmmm 

Here is a first screencast: https://www.youtube.com/watch?v=A-TvSjAU1pk&feature=youtu.be

Tomorrow I'll work on styling the data export panel to add it to the screencast also.

How long should the screencast be in your opinion ? 

Also I found out we need to agree on some vocabulary for those counting lines, are they counting lines, counting area , ... 

Also a small point regarding design, @mmmmmmmmmmmmmmmm when you work back on sketch, something that could simplify a lot my work it to have all the icons in contained in the same square 20px x 20px (for example, doesn't matter as it is vectorial), they can have more of less padding depending on what is the icon, but this way I can have them displayed with the same ratio in a button without tweaking them manually.

**Comment by b-g** [comment]
Hi @tdurand, Great!

> How long should the screencast be in your opinion?

+/- 60sec ... max 1.5 min

> Also I found out we need to agree on some vocabulary for those counting lines, are they counting lines, counting area , ...

Test Header Menu:
Live View, Counter, Pathfinder, Data, Console

Record button label:
Start Recording
Stop Recording

Counter:
1. Draw to define the counting zones (crossing vehicles increase counter by 1)
2. Counter name

@mmmmmmmmmmmmmmmm will post the WIP layout any minute

**Comment by tdurand** [comment]
Great, I was thinking of doing the normal flow:

- launch app
- check path view
- enter counter mode
- draw line
- record
- and then show the data export panel

Sounds good ?

**Comment by tdurand** [comment]
PS: I'm a bit sick since yesterday 🤒, so I might only post the final thing on the week-end

**Comment by mmmmmmmmmmmmmmmm** [comment]
Hi, here is the WIP layout and a few mock-ups for the submission.

@tdurand I think the icons still need another iteration, I will then do them in 20px x 20px. But for next week I will leave them like they are, if that's fine. 

![artboard](https://user-images.githubusercontent.com/12696639/53966530-a3bfd700-40f3-11e9-9c8e-ce2c41946121.jpg)

![mobile1](https://user-images.githubusercontent.com/12696639/53966541-a7535e00-40f3-11e9-84a1-29bddbe1827a.jpg)

![mobile2](https://user-images.githubusercontent.com/12696639/53966555-ad493f00-40f3-11e9-92bb-885e82741d41.png)

![tablet1](https://user-images.githubusercontent.com/12696639/53966560-b0442f80-40f3-11e9-8cfe-35184604e16d.png)

**Comment by b-g** [comment]
@tdurand Oh no! Get well soon! 🤒 Flow is good IMO ✅

**Comment by tdurand** [comment]
Thanks for the update, I'll try to post a screencast tomorrow looking as good as I can but it will most likely be late evening for you. But you'll have something on monday to showcase.

**Comment by tdurand** [comment]
Ok , here is a 1 min screencast you can use to showcase this new version, hopefully will be useful.

Was able only to commit 2 days last week as I've been a bit sick, the UI is getting pretty complete but still things to do. Maybe a meeting late next week would be interesting, friday ?

https://my.pcloud.com/publink/show?code=XZ6XCq7ZboOirCB7Vf7ueuOF7IwNbhuA3etk

**Comment by b-g** [comment]
Hi @tdurand, hope you are feeling better now! Many thanks for the video, perfect! Yes, lets catch up on Friday. See invite. Looking forward!

**Comment by tdurand** [comment]
For tomorrow nothing "visual" to show in addition to the screencast, but I have the opendatacam v2 running smoothly on the jetson with the new UI... I think the agenda will mainly be:

- refining UI design
- discuss features to include / exclude for the first release of v2

**Comment by b-g** [comment]
And in addition:
* [CompCars dataset](http://mmlab.ie.cuhk.edu.hk/datasets/comp_cars/index.html)
* [Automatic License Plate Recognition Based on YOLO](https://arxiv.org/abs/1802.09567)

**Comment by mmmmmmmmmmmmmmmm** [comment]
I added a few more things:
1. openmoji icons
2. adapted interface
2. fps info

@tdurand, regarding the icon size. Can we scale them to 20px in CSS, that is how I usually do it? In sketch the icons become distorted when I scale them down..

Regarding the API, lets discuss on Friday what API interface we exactly want to have, then I will include it to the interface.

![Artboard 2](https://user-images.githubusercontent.com/12696639/55090829-164b2380-50b0-11e9-91fa-08e1f9c97d82.jpg)

**Comment by tdurand** [comment]
Thanks 👍

- Of course you can do whatever size in the sketch file as it's vectorial then it's adapted, I just need that all the icon have a consistent proportion.

- Once you have Dark / Light mode settled, please send me the sketch file with both it it

- Yes we can discuss that on friday, but I think we would do an extra button on the right toolbar with console and data... or in the menu .. And then I think I would think about the content and what makes sense to include there

**Comment by mmmmmmmmmmmmmmmm** [comment]
Great, thanks! @tdurand I sent you the sketch file!

**Comment by tdurand** [comment]
Some update on this, I worked on it the past 2 days, no yet finished.. but some substancial improvements have been made to be UI & Feature complete. If you want to try it you can follow the README section about starting in simulation mode: https://github.com/moovel/lab-opendatacam/tree/v2#run-simulation-mode

Or view this quick screencast: 

Not requesting for review for now, here is a quick list of remaining task to finish before:

- [ ] Loading screen (init neural network) should have access to the console to see if there was any error
- [ ] Data view screen: Optimize perfs (currently re-render every tick) + only render current recording if page = 0 + Make download data buttons download files
- [ ] Add footer in side menu
- [ ] Persists user settings
- [ ] Implement action behind Toggle Pathfinder & Counter (currently don't do anything)
- [ ] Work on mobile responsiveness

Later improvements

- [ ] Add routing to be able to use back button
- [ ] Idea, would be great to have a visual way to get sense of where the tracker is doing well and do not do much reassignements.. for now it kind of look the same in the Liveview

**Comment by tdurand** [comment]
_Current state screencast link: https://youtu.be/m7C9oK_B-3c_

**Comment by tdurand** [comment]
Latest update screencast: https://youtu.be/TeVjVcKVJbY

Todo list is on the first post of the issue 😉

Almost there ✌️

**Comment by b-g** [comment]
@tdurand Thanks + Mega!

**Comment by tdurand** [comment]
Ok, we are now feature complete + responsive down to Iphone SE screens in landscape ... I think @mmmmmmmmmmmmmmmm now will be a good time for you to have a look and see if we can make some other quick wins...

There is still some improvements to make on the mobile experience, I've noticed that safari mobile has some weird issue with 100% height not equivalent to innerHeight reading from javascript, and on Android chrome when you close the input to give the name of an area it then does re-render canvas properly....

I'll leave this open and dedicate time as we test more, I listed some todo's in the first post of this issue

NB: to run simulation mode on your local machine, here is how to do it : https://github.com/moovel/lab-opendatacam/blob/v2/doc/DEVELOPMENT_NOTES.md#run-simulation-mode

**Comment by mmmmmmmmmmmmmmmm** [comment]
@tdurand I had a look and I think it would be good to change the following:

0. change font-face to work-sans medium -> https://fonts.google.com/specimen/Work+Sans

1. adapt border radius and size of the other buttons to this button
<img width="637" alt="Screen Shot 2019-05-29 at 15 05 21" src="https://user-images.githubusercontent.com/12696639/58559685-f5c05680-8223-11e9-8918-6a3be2d169c0.png">

2. remove blue as a hover and highlight color, grey background is enough and will be less confusing with all the other colors in the various modes
<img width="367" alt="Screen Shot 2019-05-29 at 15 06 01" src="https://user-images.githubusercontent.com/12696639/58559789-27d1b880-8224-11e9-9e4d-8e9ce5d27b69.png">

3. less line height, new row for "(crossing vehicles ...)", OK button needs more width, probably double of what's currently there
<img width="388" alt="Screen Shot 2019-05-29 at 15 06 10" src="https://user-images.githubusercontent.com/12696639/58559866-4cc62b80-8224-11e9-902e-55231ca7340d.png">

4. change the height of the buttons with icons inside to the height of the menu buttons on top
<img width="124" alt="Screen Shot 2019-05-29 at 15 06 21" src="https://user-images.githubusercontent.com/12696639/58560323-2e146480-8225-11e9-876e-8ab73ae27b67.png">

same with the X button:
<img width="70" alt="Screen Shot 2019-05-29 at 15 08 12" src="https://user-images.githubusercontent.com/12696639/58560342-379dcc80-8225-11e9-8144-b0d2f0e38fed.png">

5. change the blue background to black background, we didn't use this color so far...so I suggest to stay with black
<img width="284" alt="Screen Shot 2019-05-29 at 15 06 56" src="https://user-images.githubusercontent.com/12696639/58560399-5603c800-8225-11e9-8584-dbe79fc3e54b.png">

**Comment by tdurand** [comment]
Many thanks for this "external" eye 😉 for quick wins on UI improvements , will do next week !

**Comment by mmmmmmmmmmmmmmmm** [comment]
Thanks :)

**Comment by tdurand** [comment]
Ok, ui fixes done , will leave this issue open as there is still more to do but more time consuming.

**Comment by tdurand** [comment]
Closing this in favor of https://github.com/opendatacam/opendatacam/issues/96
